import type { MetricId, ReportOs, ReportTypeDefinition, ReportTypeId } from '@/shared/reports/types'

const personalTypes: ReportTypeDefinition[] = [
  {
    id: 'productivity',
    os: 'personal',
    title: 'Productivity Report',
    description: 'Overall personal productivity, completion, and focus areas.',
    defaultMetrics: ['tasks_completed', 'completion_rate', 'overdue_tasks', 'open_tasks', 'productivity_trend'],
    sections: ['cover', 'executive_summary', 'key_metrics', 'charts', 'detailed_analysis', 'ai_insights', 'recommendations'],
  },
  {
    id: 'weekly_productivity',
    os: 'personal',
    title: 'Weekly Productivity Report',
    description: 'This week’s completed work, backlog pressure, and next priorities.',
    defaultMetrics: ['tasks_completed', 'tasks_created', 'overdue_tasks', 'upcoming_deadlines'],
    sections: ['cover', 'executive_summary', 'key_metrics', 'charts', 'tasks', 'recommendations'],
  },
  {
    id: 'monthly_productivity',
    os: 'personal',
    title: 'Monthly Productivity Report',
    description: 'Month-level output, trends, and project progress.',
    defaultMetrics: ['tasks_completed', 'completion_rate', 'project_progress', 'productivity_trend'],
    sections: ['cover', 'executive_summary', 'key_metrics', 'charts', 'projects', 'ai_insights', 'recommendations'],
  },
  {
    id: 'task',
    os: 'personal',
    title: 'Task Report',
    description: 'Task inventory by status, priority, and due dates.',
    defaultMetrics: ['open_tasks', 'tasks_completed', 'overdue_tasks', 'upcoming_deadlines'],
    sections: ['cover', 'key_metrics', 'charts', 'tasks', 'appendix'],
  },
  {
    id: 'overdue_tasks',
    os: 'personal',
    title: 'Overdue Tasks Report',
    description: 'Everything past due with urgency and project context.',
    defaultMetrics: ['overdue_tasks', 'open_tasks'],
    sections: ['cover', 'executive_summary', 'key_metrics', 'tasks', 'recommendations'],
  },
  {
    id: 'completed_work',
    os: 'personal',
    title: 'Completed Work Report',
    description: 'What shipped in the selected period.',
    defaultMetrics: ['tasks_completed', 'completion_rate'],
    sections: ['cover', 'executive_summary', 'key_metrics', 'charts', 'tasks'],
  },
  {
    id: 'project',
    os: 'personal',
    title: 'Project Report',
    description: 'Project portfolio snapshot with health and progress.',
    defaultMetrics: ['project_count', 'project_progress', 'project_health', 'open_tasks'],
    sections: ['cover', 'key_metrics', 'charts', 'projects', 'ai_insights'],
  },
  {
    id: 'project_progress',
    os: 'personal',
    title: 'Project Progress Report',
    description: 'Completion percentage and remaining work by project.',
    defaultMetrics: ['project_progress', 'tasks_completed', 'open_tasks'],
    sections: ['cover', 'key_metrics', 'charts', 'projects', 'tasks'],
  },
  {
    id: 'project_health',
    os: 'personal',
    title: 'Project Health Report',
    description: 'Health states, blockers, and stalled work.',
    defaultMetrics: ['project_health', 'overdue_tasks', 'open_tasks'],
    sections: ['cover', 'executive_summary', 'key_metrics', 'projects', 'recommendations'],
  },
  {
    id: 'roadmap_progress',
    os: 'personal',
    title: 'Roadmap Progress Report',
    description: 'Roadmap items and delivery horizon progress.',
    defaultMetrics: ['project_progress', 'upcoming_deadlines'],
    sections: ['cover', 'key_metrics', 'projects', 'appendix'],
  },
  {
    id: 'workload',
    os: 'personal',
    title: 'Workload Report',
    description: 'Open load versus completed throughput.',
    defaultMetrics: ['workload', 'open_tasks', 'tasks_completed', 'overdue_tasks'],
    sections: ['cover', 'key_metrics', 'charts', 'tasks', 'recommendations'],
  },
  {
    id: 'time_allocation',
    os: 'personal',
    title: 'Time Allocation Report',
    description: 'Where estimated effort is concentrated across projects.',
    defaultMetrics: ['time_allocation', 'project_progress', 'open_tasks'],
    sections: ['cover', 'key_metrics', 'charts', 'projects', 'ai_insights'],
  },
  {
    id: 'ai_activity',
    os: 'personal',
    title: 'AI Activity Report',
    description: 'AI-assisted activity and recommended next moves.',
    defaultMetrics: ['ai_insights', 'tasks_completed', 'open_tasks'],
    sections: ['cover', 'executive_summary', 'ai_insights', 'recommendations'],
  },
  {
    id: 'custom',
    os: 'personal',
    title: 'Custom Report',
    description: 'Configure metrics yourself or ask AI to shape the report.',
    defaultMetrics: ['tasks_completed', 'overdue_tasks', 'open_tasks', 'project_progress', 'ai_insights'],
    sections: ['cover', 'executive_summary', 'key_metrics', 'charts', 'detailed_analysis', 'ai_insights', 'recommendations'],
  },
]

const workspaceTypes: ReportTypeDefinition[] = [
  {
    id: 'workspace_overview',
    os: 'workspace',
    title: 'Workspace Overview',
    description: 'Organization-wide projects, tasks, and health.',
    defaultMetrics: ['project_count', 'open_tasks', 'tasks_completed', 'overdue_tasks', 'project_health'],
    sections: ['cover', 'executive_summary', 'key_metrics', 'charts', 'projects', 'ai_insights', 'recommendations'],
  },
  {
    id: 'team_performance',
    os: 'workspace',
    title: 'Team Performance Report',
    description: 'Team throughput, overdue load, and delivery risk.',
    defaultMetrics: ['tasks_completed', 'completion_rate', 'overdue_tasks', 'member_workload'],
    sections: ['cover', 'executive_summary', 'key_metrics', 'charts', 'teams', 'recommendations'],
    needsTeams: true,
    needsMembers: true,
  },
  {
    id: 'department_performance',
    os: 'workspace',
    title: 'Department Performance Report',
    description: 'Department-level workload and progress.',
    defaultMetrics: ['open_tasks', 'tasks_completed', 'overdue_tasks', 'workload'],
    sections: ['cover', 'key_metrics', 'charts', 'teams', 'projects', 'recommendations'],
    needsDepartments: true,
  },
  {
    id: 'team_workload',
    os: 'workspace',
    title: 'Team Workload Report',
    description: 'Capacity and assignment pressure across members.',
    defaultMetrics: ['member_workload', 'team_capacity', 'overdue_tasks', 'open_tasks'],
    sections: ['cover', 'key_metrics', 'charts', 'teams', 'tasks', 'recommendations'],
    needsTeams: true,
    needsMembers: true,
  },
  {
    id: 'project_progress',
    os: 'workspace',
    title: 'Project Progress Report',
    description: 'Shared project progress and remaining work.',
    defaultMetrics: ['project_progress', 'open_tasks', 'tasks_completed', 'project_health'],
    sections: ['cover', 'key_metrics', 'charts', 'projects', 'tasks'],
  },
  {
    id: 'project_health',
    os: 'workspace',
    title: 'Project Health Report',
    description: 'Health distribution and blocked/stalled projects.',
    defaultMetrics: ['project_health', 'overdue_tasks', 'open_tasks'],
    sections: ['cover', 'executive_summary', 'key_metrics', 'projects', 'recommendations'],
  },
  {
    id: 'overdue_tasks',
    os: 'workspace',
    title: 'Overdue Tasks Report',
    description: 'Organizational overdue work by project and assignee.',
    defaultMetrics: ['overdue_tasks', 'member_workload', 'open_tasks'],
    sections: ['cover', 'key_metrics', 'tasks', 'teams', 'recommendations'],
    needsMembers: true,
  },
  {
    id: 'completed_work',
    os: 'workspace',
    title: 'Completed Work Report',
    description: 'Completed delivery across the workspace.',
    defaultMetrics: ['tasks_completed', 'completion_rate'],
    sections: ['cover', 'key_metrics', 'charts', 'tasks', 'projects'],
  },
  {
    id: 'sprint',
    os: 'workspace',
    title: 'Sprint Report',
    description: 'Period delivery snapshot suitable for sprint reviews.',
    defaultMetrics: ['tasks_completed', 'open_tasks', 'overdue_tasks', 'completion_rate'],
    sections: ['cover', 'executive_summary', 'key_metrics', 'charts', 'tasks', 'recommendations'],
  },
  {
    id: 'workload',
    os: 'workspace',
    title: 'Workload Report',
    description: 'Workspace load balancing and bottlenecks.',
    defaultMetrics: ['workload', 'member_workload', 'overdue_tasks', 'open_tasks'],
    sections: ['cover', 'key_metrics', 'charts', 'teams', 'ai_insights', 'recommendations'],
    needsMembers: true,
  },
  {
    id: 'ai_activity',
    os: 'workspace',
    title: 'AI Activity Report',
    description: 'AI recommendations and organizational insights.',
    defaultMetrics: ['ai_insights', 'overdue_tasks', 'project_health'],
    sections: ['cover', 'executive_summary', 'ai_insights', 'recommendations'],
  },
  {
    id: 'custom',
    os: 'workspace',
    title: 'Custom Report',
    description: 'Build an executive or operational report with AI assistance.',
    defaultMetrics: ['tasks_completed', 'overdue_tasks', 'project_progress', 'member_workload', 'ai_insights'],
    sections: ['cover', 'executive_summary', 'key_metrics', 'charts', 'projects', 'teams', 'ai_insights', 'recommendations'],
    needsDepartments: true,
    needsTeams: true,
    needsMembers: true,
  },
]

export function listReportTypes(os: ReportOs): ReportTypeDefinition[] {
  const source = os === 'personal' ? personalTypes : workspaceTypes
  return source.filter((item) => item.os === os || item.os === 'both')
}

export function getReportType(os: ReportOs, id: ReportTypeId): ReportTypeDefinition {
  return listReportTypes(os).find((item) => item.id === id) ?? listReportTypes(os)[0]!
}

export const ALL_METRICS: Array<{ id: MetricId; label: string; os: ReportOs | 'both' }> = [
  { id: 'tasks_created', label: 'Tasks created', os: 'both' },
  { id: 'tasks_completed', label: 'Tasks completed', os: 'both' },
  { id: 'completion_rate', label: 'Completion rate', os: 'both' },
  { id: 'overdue_tasks', label: 'Overdue tasks', os: 'both' },
  { id: 'open_tasks', label: 'Open tasks', os: 'both' },
  { id: 'project_count', label: 'Projects', os: 'both' },
  { id: 'project_progress', label: 'Project progress', os: 'both' },
  { id: 'project_health', label: 'Project health', os: 'both' },
  { id: 'time_allocation', label: 'Time allocation', os: 'both' },
  { id: 'workload', label: 'Workload', os: 'both' },
  { id: 'member_workload', label: 'Member workload', os: 'workspace' },
  { id: 'team_capacity', label: 'Team capacity', os: 'workspace' },
  { id: 'productivity_trend', label: 'Productivity trends', os: 'both' },
  { id: 'upcoming_deadlines', label: 'Upcoming deadlines', os: 'both' },
  { id: 'ai_insights', label: 'AI insights', os: 'both' },
]

export function metricsForOs(os: ReportOs) {
  return ALL_METRICS.filter((metric) => metric.os === os || metric.os === 'both')
}
