import { supabase } from '@/lib/supabase/client'
import { recordActivity } from '@/features/activity/record'
import { requireUserId } from '@/lib/supabase/activity'
import type { ReportSnapshot } from '@/shared/reports/types'
import type { Json } from '@/types/database'
import { type StoredReportRow } from '@/shared/reports/storage'

export type { StoredReportRow } from '@/shared/reports/storage'
export { rowToSnapshot } from '@/shared/reports/storage'

function snapshotToHtmlSummary(snapshot: ReportSnapshot) {
  const metrics = snapshot.metrics
    .map((m) => `<li><strong>${escapeHtml(m.label)}:</strong> ${escapeHtml(String(m.value))}</li>`)
    .join('')
  return `
    <article data-hilm-report="1">
      <h1>${escapeHtml(snapshot.title)}</h1>
      <p>Generated by ${escapeHtml(snapshot.generatedBy)} on ${escapeHtml(snapshot.generatedAt)}</p>
      <p>Period: ${escapeHtml(snapshot.periodStart)} → ${escapeHtml(snapshot.periodEnd)}</p>
      <ul>${metrics}</ul>
      <p>${escapeHtml(snapshot.executiveSummary)}</p>
    </article>
  `.trim()
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function enginePayload(snapshot: ReportSnapshot) {
  return {
    report_type: snapshot.typeId,
    title: snapshot.title,
    content_html: snapshotToHtmlSummary(snapshot),
    branding: {
      productName: snapshot.branding.productName,
      accent: snapshot.branding.accent,
      logoUrl: snapshot.branding.logoUrl ?? null,
      workspaceName: snapshot.workspaceName ?? null,
      engineVersion: 1,
      snapshot,
      config: snapshot.config,
      periodStart: snapshot.periodStart,
      periodEnd: snapshot.periodEnd,
      generatedByName: snapshot.generatedBy,
      status: 'ready',
    } as Json,
    period_start: snapshot.periodStart,
    period_end: snapshot.periodEnd,
    generated_by_name: snapshot.generatedBy,
    status: 'ready',
    config: snapshot.config as unknown as Json,
    snapshot: snapshot as unknown as Json,
  }
}

function isMissingColumnError(message: string) {
  const lower = message.toLowerCase()
  return (
    lower.includes('period_start') ||
    lower.includes('generated_by_name') ||
    lower.includes('snapshot') ||
    lower.includes('column') ||
    lower.includes('schema cache')
  )
}

export async function savePersonalReport(snapshot: ReportSnapshot) {
  const userId = await requireUserId()
  const payload = enginePayload(snapshot)

  const full = await supabase
    .from('ai_reports')
    .insert({ user_id: userId, ...payload })
    .select('*')
    .single()

  let data: StoredReportRow
  if (full.error) {
    if (!isMissingColumnError(full.error.message)) throw full.error
    const legacy = await supabase
      .from('ai_reports')
      .insert({
        user_id: userId,
        report_type: payload.report_type,
        title: payload.title,
        content_html: payload.content_html,
        branding: payload.branding,
      })
      .select('*')
      .single()
    if (legacy.error) throw legacy.error
    data = legacy.data as StoredReportRow
  } else {
    data = full.data as StoredReportRow
  }

  await recordActivity({
    userId,
    entityType: 'report',
    entityId: data.id,
    action: 'generated',
    summary: `Report Generated · ${snapshot.title} · Generated by ${snapshot.generatedBy}`,
    metadata: {
      typeId: snapshot.typeId,
      periodStart: snapshot.periodStart,
      periodEnd: snapshot.periodEnd,
      os: 'personal',
    },
  })

  return data
}

export async function listPersonalReports() {
  const userId = await requireUserId()
  const { data, error } = await supabase
    .from('ai_reports')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(30)
  if (error) throw error
  return (data ?? []) as StoredReportRow[]
}
